packages:
  - "backend"
  - "frontend"
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@swc/core': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  workerd: true
