// Refleja backend/src/common/problem-details/error-code.enum.ts.
export enum ErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  CATALOG_VALUE_INVALID = 'CATALOG_VALUE_INVALID',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  QUOTE_NOT_FOUND = 'QUOTE_NOT_FOUND',
  POLICY_NOT_FOUND = 'POLICY_NOT_FOUND',
  POLICY_ALREADY_ISSUED = 'POLICY_ALREADY_ISSUED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
